{% set name = "ripfind" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matthiasdiener/ripfind/archive/refs/tags/{{ version }}.tar.gz
  sha256: b9d0d2a8890b3bae58b92bd58144223f1de694cba1b0e5c66b80b110c434648a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - rf --help  # [build_platform == target_platform]

about:
  home: https://github.com/matthiasdiener/ripfind
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A fast and lean replacement for the find command
  description: |
    A fast and lean replacement for the find command, modeled after the ripgrep
    package

extra:
  recipe-maintainers:
    - matthiasdiener
