{% set name = "ripfind" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matthiasdiener/ripfind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d49b05f4b34a68fa1d276a6dc32de62302b60bff43202200bbea2e5b9b0b350b

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - rf --help  # [build_platform == target_platform]

about:
  home: https://github.com/matthiasdiener/ripfind
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A fast and lean replacement for the find command
  description: |
    A fast and lean replacement for the find command, modeled after the ripgrep
    package

extra:
  recipe-maintainers:
    - matthiasdiener
